### ISSUE TITLE
Literally none of these work properly.

### ISSUE THREAD

**Issue by githubisveryepic** [Blantados/blantados-funkin-utau-main#1]
It's either silence or someone after eating taco bell.

You REALLY got us good, haven't you? You trolled people who wanted to use this.

**Comment by Blantados** [comment]
Are you sure you're using them correctly? I've used these and they work just fine. Be sure to test with other resamplers as well

**Comment by Domino054** [comment]
My guess is that some of the voicebanks don't have a proper oto.ini.

**Comment by aditgitu37** [comment]
Halo
