### ISSUE TITLE
Matt (Wii) only has A and O.

### ISSUE THREAD

**Issue by githubisveryepic** [Blantados/blantados-funkin-utau-main#2]
Where's all the other sounds?

**Comment by ACardboardBox1** [comment]
> 
> 
> Where's all the other sounds?
maybe he doesnt need them?
for example, the monika voicebank in genox's voicebank only has a, because it the only sound she needs.

**Comment by githubisveryepic** [comment]
bruh i was stupid when i wrote this lol
